#!/usr/bin/env bash
# makes redirect_me redirect to another page
apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sed -i '29 i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart
