#!/usr/bin/env bash
# configures Nginx server to have a custom 404 page
# 404 page will contain the string `Ceci n'est pas une page`
apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sed -i '29 i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sed -i '30 i error_page 404 /404.html;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
service nginx restart
