#!/usr/bin/env bash
# shellcheck disable=SC2154
# configure nginx so its HTTP response contains customer header
sudo apt-get update
sudo apt-get -y install nginx
service nginx start
sudo sed -i '25 i \add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
