#!/usr/bin/env bash
# displays a list of currently running processes
ps -auxf
# a - selects all processes
# u - selects all processes on a terminal, including those of other users
# x - selects processes without controlling ttys
# f - shows ASCII-art process hierarchy
