#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# script should only display: username, group id, home directory path for the user
# must use while loop. for and until are forbidden
while IFS= read passwd
do
    echo "$passwd" | cut -d: -f1,4,6
done < /etc/passwd
