#!/usr/bin/env bash
#Display Holberton School 10 times, but for 9th iteration, display Hi
count=0
while [ $count -le 10 ]
do
    echo Holberton School
    if [ $count = 8 ]; then
        echo Hi
        count=$((count + 1))
    fi
    count=$((count + 1))
done
