#!/usr/bin/env bash
#Loops 1 to 10, 4th Bad Luck, 5th Good Luck, else Holberton School
count=1
while [ $count -le 10 ]
do
    if [ $count = 4 ]; then
        echo bad luck
    elif [ $count = 8 ]; then
        echo good luck
    else
        echo Holberton School
    fi
    count=$((count + 1))
done
