#!/usr/bin/env bash
#Displays 1-20, do something on 4th, 9th, and 17th iteratioon using while loop and case
count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        4)  
            echo bad luck from China
            ;;
        9)
            echo bad luck from Japan
            ;;
        17)
            echo bad luck from Italy
            ;;
    esac
    count=$((count + 1))
done
