#!/usr/bin/env bash
#Displays content of current directory in list format and only shows what is after the dash
list="$(ls)"
for i in $list
do
    i=$(echo "$i" | cut -d'-' -f1 --complement)
    echo "$i"
done 
